### ISSUE TITLE
Upgrade the project meta data to support new catalog commands

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-cloud-optimize#32]
Add metadata to the repository that matches the example laid out here.
- [x] Add a `config.json` file to a `catalog` directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/config.json).
- [x] Move the `/screenshots` directory into `catalog`:
    - [x] Update the screenshot file names ([to match this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/documentation.md))
    - [x] Update the screenshot links in the `README.md`.
- [x] Add [the new header image](https://newrelic.slack.com/archives/GNR5YH7HP/p1583418095011300) to the top of `README.md`.
- [x] Add a documentation.md file to a catalog directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/documentation.md).
    - [x] Update the relative paths in `documentation.md` to be absolute paths
- [ ] **N/A** ~(Optional) If there's additional documentation referenced in the repo, add a `additionalInfo.md` file to a `catalog` directory in the repo root, [matching this format](https://github.com/newrelic/nr1-catalog/blob/master/examples/catalog/additionalInfo.md).~
- [x] Ensure the `README.md` commands section matches [Justin's snippet](https://newrelic.slack.com/archives/GNR5YH7HP/p1583420716020000).
- [x] Run `npm start` and let the CLI move the `nr1.json`
    - [x] Edit that file to make sure the name and description make sense.
