### ISSUE TITLE
Tracking: refactor nerdlets/cloud-optimize-apm/cloud-optimize-apm.js

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-cloud-optimize#39]
nerdlets/cloud-optimize-apm/cloud-optimize-apm.js contains four linting errors that are currently addressed through disabling the checks. The appropriate remediation is to refactor the code. The issues are:

- [ ] calling `setState` in the `componentDidUpdate` method
- [ ] async resolver to a Promise in `handleParentState`
- [ ] async resolver to a Promise in `fetchContainerPerformanceData`
- [ ] async resolver to a Promise in `fetchHostPerformance`

**Comment by Kav91** [comment]
@tangollama I'll be rewriting the entire nerdpack starting next week.
The work should resolve this, and #38. Leave these two with me.

**Comment by tangollama** [comment]
Sounds great @Kav91. When I was going through the review, I just wanted/needed to make sure I kept tabs on what we might look at when reviewing roadmap/backlogs. Thanks for the heads up.
